version: 2.1
executors:
  perl-mariadb:
    parameters:
      perl:
        type: string
      mariadb:
        type: string
    docker:
      - image: perl:<< parameters.perl >>-threaded
      - image: circleci/mariadb:<< parameters.mariadb >>
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: koha
          MYSQL_USER: koha
          MYSQL_PASSWORD: koha
      - image: memcached
      - image: koha/elasticsearch-icu:6.x
        environment:
          discovery.type: single-node
          ES_JAVA_OPTS: '-Xms512m -Xmx512m'
    working_directory: /app/koha
    environment:
      PERL5LIB: /app/koha:/app/.local/lib/perl5
      KOHA_CONF: /app/koha/.circleci/koha-conf.xml
  perl-mysql:
    parameters:
      perl:
        type: string
      mysql:
        type: string
    docker:
      - image: perl:<< parameters.perl >>-threaded
      - image: circleci/mysql:<< parameters.mysql >>
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: koha
          MYSQL_USER: koha
          MYSQL_PASSWORD: koha
        command: --default-authentication-plugin=mysql_native_password --sort-buffer-size=2097152
      - image: memcached
      - image: koha/elasticsearch-icu:6.x
        environment:
          discovery.type: single-node
          ES_JAVA_OPTS: '-Xms512m -Xmx512m'
    working_directory: /app/koha
    environment:
      PERL5LIB: /app/koha:/app/.local/lib/perl5
      KOHA_CONF: /app/koha/.circleci/koha-conf.xml

jobs:
  test:
    parameters:
      e:
        type: executor
    executor: << parameters.e >>
    steps:
      - checkout

      - run:
          name: Install system dependencies
          command: |
            apt-get update
            apt-get install -y \
                at \
                fonts-dejavu \
                gettext \
                idzebra-2.0 \
                libfribidi-dev \
                libgd-dev \
                libyaz-dev \
                locales
            localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

      - run:
          name: Install Perl dependencies
          environment:
            PERL_CPANM_OPT: --quiet --metacpan --notest --local-lib-contained /app/.local
          command: |
            cpanm --installdeps .
            cpanm AnyEvent \
                AnyEvent::HTTP \
                Archive::Extract \
                Array::Utils \
                Catmandu::MARC \
                Catmandu::Store::ElasticSearch~'>= 0.0507, <= 0.512' \
                CGI::Session::Driver::memcached \
                HTTP::OAI~'<4' \
                HTTPD::Bench::ApacheBench \
                LWP::Protocol::https \
                Module::Bundled::Files \
                Net::LDAP \
                Net::Netmask~'<1.9104' \
                Net::OAuth2::AuthorizationServer \
                Net::Server::PreFork \
                Net::SFTP::Foreign \
                Net::Z3950::SimpleServer \
                Parallel::ForkManager \
                PPI \
                Readonly \
                Readonly::XS \
                SMS::Send::Test \
                Sys::CPU \
                TAP::Harness::JUnit \
                Test::DBIx::Class \
                Test::MockTime \
                Test::Strict \
                Test::WWW::Mechanize \
                Time::Fake \
                UNIVERSAL::require \
                WebService::ILS \
                XML::LibXML~'<2.0202' \
                XML::Writer \
                YAML::Syck~'<1.32'

      # Graphics::Magick is not on CPAN, we have to build it manually
      - run:
          name: Install Graphics::Magick
          working_directory: /app
          command: |
            wget https://downloads.sourceforge.net/project/graphicsmagick/graphicsmagick/1.3.35/GraphicsMagick-1.3.35.tar.gz
            tar xf GraphicsMagick-1.3.35.tar.gz
            cd GraphicsMagick-1.3.35
            ./configure --enable-shared
            make
            make install
            cd PerlMagick
            perl Makefile.PL INSTALL_BASE=/app/.local
            make
            make install

      - run:
          name: Populate database
          command: perl .circleci/populate-database.pl

      # Those tests should be automatically skipped but they are not
      - run:
          name: Remove tests that should not be run
          command: |
            rm -f t/db_dependent/selenium/administration_tasks.t
            rm -f t/db_dependent/selenium/regressions.t
            rm -f t/db_dependent/selenium/patrons_search.t
            rm -f t/db_dependent/selenium/update_child_to_adult.t
            rm -f t/db_dependent/www/regressions.t

      # /usr/bin/perl can be a different version of the one we want to use
      # Change the shebang so that it uses the correct perl version
      - run:
          name: Fix shebangs of Perl scripts executed by tests
          command: sed -i 's/#!\/usr\/bin\/perl/#!\/usr\/bin\/env perl/' t/db_dependent/default_search_class.pl t/db_dependent/zebra_config.pl

      - run:
          name: Run tests
          environment:
            KOHA_PROVE_CPUS: 2
            JUNIT_OUTPUT_FILE: test-results/main/results.xml
            JUNIT_NAME_MANGLE: perl
          # t/Logger.t fails if run as root, so run tests as a normal user
          command: |
            adduser --quiet --disabled-password --gecos '' koha
            mkdir -p test-results/main
            chown -R koha:koha test-results
            su -c 'prove --nocount --timer --harness TAP::Harness::JUnit --recurse t' koha

      - store_test_results:
          path: test-results

workflows:
  version: 2
  test:
    jobs:
      - test:
          name: perl:5.26 mariadb:10.1
          e:
            name: perl-mariadb
            perl: '5.26'
            mariadb: '10.1'
      - test:
          name: perl:5.26 mariadb:10.2
          e:
            name: perl-mariadb
            perl: '5.26'
            mariadb: '10.2'
      - test:
          name: perl:5.26 mariadb:10.3
          e:
            name: perl-mariadb
            perl: '5.26'
            mariadb: '10.3'
      - test:
          name: perl:5.26 mariadb:10.4
          e:
            name: perl-mariadb
            perl: '5.26'
            mariadb: '10.4'
      - test:
          name: perl:5.26 mysql:5.7
          e:
            name: perl-mysql
            perl: '5.26'
            mysql: '5.7'
      - test:
          name: perl:5.26 mysql:8
          e:
            name: perl-mysql
            perl: '5.26'
            mysql: '8'
      - test:
          name: perl:5.28 mariadb:10.4
          e:
            name: perl-mariadb
            perl: '5.28'
            mariadb: '10.4'
      - test:
          name: perl:5.30 mariadb:10.4
          e:
            name: perl-mariadb
            perl: '5.30'
            mariadb: '10.4'
